["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "."

["protostar.contracts"]
storage = [ 
    "./exercises/contracts/storage/storage.cairo"
]

["protostar.shared_command_configs"]
cairo_path = ["./libs/cairo_contracts/src"]